package com.here.xyz.models.hub;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.here.xyz.models.geojson.implementation.Feature;
import org.jetbrains.annotations.Nullable;

@JsonTypeName(value = "Storage")
public class Storage extends Feature {

  public static final String STORAGE_ID = "storageId";

  /**
   * Create a new empty storage.
   *
   * @param id        the unique identifier of the feature (selected by the user).
   * @param storageId the unique identifier (40-bit unsigned integer) that is auto-generated by the Naksha-Hub.
   */
  public Storage(@JsonProperty(ID) @Nullable String id, @JsonProperty(STORAGE_ID) long storageId) {
    super(id);
  }

  /**
   * The unique storage identifier, being a 40-bit unsigned integer.
   */
  @JsonProperty(STORAGE_ID)
  public long storageId;

}