curations:
  license_findings:
    - path: "xyz-models/src/main/java/com/here/xyz/models/hub/Space.java"
      reason: "DATA_OF"
      comment: "The file contains all possible license identifiers for the content of a space."
      concluded_license: "Apache-2.0"
    - path: "xyz-hub-service/src/main/resources/openapi.*"
      reason: "DATA_OF"
      comment: "The files found in this directory are part of the OpenAPI specification which contains various license keywords, see e.g. \
        https://github.com/heremaps/xyz-hub/blob/master/xyz-hub-service/src/main/resources/webroot/openapi.yaml#L1172-L1205."
      concluded_license: "Apache-2.0"
excludes:
  paths:
  - pattern: "*/src/test/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory only contains tests to verify correct functioning of XYZ Hub. Not included in released artifacts."
  - pattern: "xyz-hub-test/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory only contains tests to verify correct functioning of XYZ Hub. Not included in released artifacts."
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Scope with dependencies provided by the JDK or container at runtime. Not included in released artifacts."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts."
resolutions:
  issues:
  - message: "ERROR: Timeout after 300 seconds while scanning file 'csv/samples/f_5500_2010_first9999.csv'."
    reason: "SCANNER_ISSUE"
    comment: "This error can be ignored as the file does not introduce any new licenses \
      compared to what is already detected for this package."
  - message: "ERROR: Timeout after 300 seconds while scanning file 'jts/testdata/polygon.wkb'."
    reason: "SCANNER_ISSUE"
    comment: "This error can be ignored as the file does not introduce any new licenses \
      compared to what is already detected for this package."