FROM postgres:15.2

ENV POSTGRES_PASSWORD password

RUN apt-get update && \
    apt-get -y install postgresql-15-postgis-3 postgresql-plpython3-15 git python3-boto3 make

WORKDIR /home
#Clone forked AWS RDS S3-Extension mock called "chimpler"
RUN git clone https://github.com/mchrza/postgres-aws-s3.git --branch 01 .
RUN make install

#Add mocked aws settings during initializiation phase
RUN echo "#!/bin/sh -e \n\
echo aws_s3.endpoint_url='http://localstack:4566' >> /var/lib/postgresql/data/postgresql.conf \n\
echo aws_s3.access_key_id='localstack' >> /var/lib/postgresql/data/postgresql.conf \n\
echo aws_s3.secret_access_key='localstack' >> /var/lib/postgresql/data/postgresql.conf \n\
psql -a -d postgres -U postgres -c \"SELECT pg_reload_conf();\" > /dev/null \n\
" > /docker-entrypoint-initdb.d/cfg_s3_dummy.sh

RUN chmod 755 /docker-entrypoint-initdb.d/cfg_s3_dummy.sh

#Increase Database Loglevel 
RUN echo "#!/bin/sh -e\n\
\n\n\
sed -i.org \
 -e \"s/#log_min_messages = warning/log_min_messages = info/\" \
 -e \"s/#log_min_error_statement = error/log_min_error_statement = info/\" \
 -e \"s/#log_statement = 'none'/log_statement = 'all'/\" \
 /var/lib/postgresql/data/postgresql.conf\n\n\
\n\n\
" > /docker-entrypoint-initdb.d/cfg_postgresql.conf.sh

RUN chmod 755 /docker-entrypoint-initdb.d/cfg_postgresql.conf.sh

