rootProject.name = "naksha"

include(":here-naksha-lib-core")
include(":here-naksha-lib-heapcache")
include(":here-naksha-lib-psql")
//include(":here-naksha-lib-extension")
include(":here-naksha-handler-activitylog")
//include(":here-naksha-handler-http")
//include(":here-naksha-handler-psql")
include(":here-naksha-lib-handlers")
include(":here-naksha-lib-hub")
include(":here-naksha-lib-view")
include(":here-naksha-common-http")
include(":here-naksha-storage-http")
include(":here-naksha-app-service")
