/*
 * Copyright (C) 2017-2026 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.xyz.jobs.util;

import com.here.xyz.jobs.steps.Config;
import com.here.xyz.util.ARN;
import com.here.xyz.util.service.aws.AwsClientFactoryBase;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import software.amazon.awssdk.services.s3control.model.CreateJobRequest;
import software.amazon.awssdk.services.s3control.model.CreateJobResponse;
import software.amazon.awssdk.services.s3control.model.JobManifestGenerator;
import software.amazon.awssdk.services.s3control.model.JobManifestGeneratorFilter;
import software.amazon.awssdk.services.s3control.model.JobOperation;
import software.amazon.awssdk.services.s3control.model.JobReport;
import software.amazon.awssdk.services.s3control.model.JobReportFormat;
import software.amazon.awssdk.services.s3control.model.JobReportScope;
import software.amazon.awssdk.services.s3control.model.KeyNameConstraint;
import software.amazon.awssdk.services.s3control.model.S3JobManifestGenerator;
import software.amazon.awssdk.services.s3control.model.S3SetObjectTaggingOperation;
import software.amazon.awssdk.services.s3control.model.S3Tag;

/**
 * Helper for running <a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops.html">S3 Batch Operations</a> jobs.
 */
public final class S3BatchOperations {

  private static final Logger logger = LogManager.getLogger();
  /**
   * Prefix (within the operated bucket) under which Batch Operations completion reports are written.
   */
  private static final String REPORT_PREFIX = "_batch-reports";
  /**
   * Default S3 Batch Operations job priority (higher = more urgent).
   */
  private static final int JOB_PRIORITY = 10;
  /**
   * The tag applied to objects that should be removed by the bucket's lifecycle rule (the "DeleteScheduledForDeletion" rule in the
   * deployment template). Objects carrying this tag are expired by S3 (currently after 1 day).
   */
  public static final String SCHEDULED_FOR_DELETION_TAG_KEY = "ScheduledForDeletion";
  public static final String SCHEDULED_FOR_DELETION_TAG_VALUE = "true";

  private S3BatchOperations() {
  }

  /**
   * Schedules all objects under the given prefixes (in the jobs bucket) for deletion by tagging them with {@code ScheduledForDeletion=true}
   * via one S3 Batch Operations job. The object list is generated by S3 from the prefixes (via an {@link S3JobManifestGenerator}). The
   * bucket's lifecycle rule then expires them.
   *
   * @param jobId    The job whose resources are being scheduled for deletion (used for the idempotency token and job tag).
   * @param prefixes The S3 key prefixes (within the jobs bucket) whose contents should be scheduled for deletion.
   * @return The created Batch Operations job id, or {@link Optional#empty()} if there was nothing to schedule.
   */
  public static Optional<String> scheduleForDeletion(String jobId, List<String> prefixes) {
    final String bucket = Config.instance.JOBS_S3_BUCKET;

    if (prefixes == null || prefixes.isEmpty()) {
      logger.info("[{}] Nothing to schedule for deletion (no prefixes).", jobId);
      return Optional.empty();
    }
    if (AwsClientFactoryBase.isLocal()) {
      deleteOutputs(bucket, jobId, prefixes);
      return Optional.empty();
    }
    return createBatchJob(bucket, jobId, prefixes);
  }

  /**
   * Directly deletes every object under the given prefixes. Used only in local environments, which have no S3 Batch Operations support.
   */
  private static void deleteOutputs(String bucket, String jobId, List<String> prefixes) {
    final S3Client s3Client = S3Client.getInstance(bucket);
    CompletableFuture.allOf(prefixes.stream()
        .map(s3Client::deleteFolder)
        .toArray(CompletableFuture[]::new)).join();
    logger.info("[{}] Deleted job resources directly under prefixes {} (local - S3 Batch Operations unavailable).", jobId, prefixes);
  }

  /**
   * Submits one S3 Batch Operations job that tags every object under {@code prefixes} with {@code ScheduledForDeletion=true}. The object
   * list is generated by S3 from the prefixes (see {@link #buildCreateJobRequest}). Returns {@link Optional#empty()} if no batch operations
   * role is configured.
   */
  private static Optional<String> createBatchJob(String bucket, String jobId, List<String> prefixes) {
    String roleArn = Config.instance.S3_BATCH_OPS_ROLE_ARN;
    if (roleArn == null || roleArn.isBlank()) {
      logger.info("[{}] Skipping S3 Batch Operations CreateJob (batchOpsRoleConfigured=false) for prefixes {}.", jobId, prefixes);
      return Optional.empty();
    }

    CreateJobResponse response = AwsClientFactory.s3ControlClient().createJob(buildCreateJobRequest(bucket, roleArn, jobId, prefixes));
    logger.info("[{}] Created S3 Batch Operations job {} to tag objects under prefixes {} for deletion.", jobId, response.jobId(),
        prefixes);
    return Optional.of(response.jobId());
  }

  /**
   * Builds a {@code PutObjectTagging} operation that replaces each object's tag set with {@code tags}.
   */
  private static JobOperation tagObjects(Map<String, String> tags) {
    List<S3Tag> tagSet = tags.entrySet().stream()
        .map(entry -> S3Tag.builder().key(entry.getKey()).value(entry.getValue()).build())
        .collect(Collectors.toList());
    return JobOperation.builder()
        .s3PutObjectTagging(S3SetObjectTaggingOperation.builder().tagSet(tagSet).build())
        .build();
  }

  /**
   * Builds a {@link CreateJobRequest} whose object list is generated by S3 from {@code prefixes} (via an {@link S3JobManifestGenerator}
   * with a {@code matchAnyPrefix} filter).
   */
  private static CreateJobRequest buildCreateJobRequest(String bucket, String roleArn, String jobId, List<String> prefixes) {
    final String accountId = accountIdOf(roleArn);
    return CreateJobRequest.builder()
        .accountId(accountId)
        .roleArn(roleArn)
        .priority(JOB_PRIORITY)
        //Run the job automatically (no manual confirmation step in the S3 console).
        .confirmationRequired(false)
        .clientRequestToken(clientRequestToken("ScheduleForDeletion-" + jobId))
        .description("Schedule objects under " + prefixes.size() + " prefix(es) of job " + jobId + " for deletion")
        // The operation is to tag the objects with ScheduledForDeletion=true, which triggers the bucket's lifecycle rule to expire them.
        .operation(tagObjects(Map.of(SCHEDULED_FOR_DELETION_TAG_KEY, SCHEDULED_FOR_DELETION_TAG_VALUE)))
        .manifestGenerator(manifestGeneratorFor(bucket, accountId, prefixes))
        .report(failedTasksReport(bucket))
        .tags(S3Tag.builder().key("jobId").value(jobId).build())
        .build();
  }

  /**
   * A manifest generator that lets S3 build the object list from {@code prefixes} ({@code matchAnyPrefix})
   */
  private static JobManifestGenerator manifestGeneratorFor(String bucket, String accountId, List<String> prefixes) {
    return JobManifestGenerator.builder()
        .s3JobManifestGenerator(S3JobManifestGenerator.builder()
            .sourceBucket("arn:aws:s3:::" + bucket)
            .expectedBucketOwner(accountId)
            .enableManifestOutput(false)
            .filter(JobManifestGeneratorFilter.builder()
                .keyNameConstraint(KeyNameConstraint.builder()
                    .matchAnyPrefix(prefixes)
                    .build())
                .build())
            .build())
        .build();
  }

  /**
   * A completion report (written under {@value #REPORT_PREFIX} in {@code bucket}) covering only the failed tasks.
   */
  private static JobReport failedTasksReport(String bucket) {
    return JobReport.builder()
        .enabled(true)
        .bucket("arn:aws:s3:::" + bucket)
        .prefix(REPORT_PREFIX)
        .format(JobReportFormat.REPORT_CSV_20180820)
        .reportScope(JobReportScope.FAILED_TASKS_ONLY)
        .build();
  }

  /**
   * Deterministic idempotency token derived from jobId, so that a retried operation reuses the same token.
   */
  private static String clientRequestToken(String jobId) {
    return UUID.nameUUIDFromBytes(jobId.getBytes(StandardCharsets.UTF_8)).toString();
  }

  /**
   * Extracts the AWS account id from an IAM role ARN ({@code arn:aws:iam::<accountId>:role/<name>}), reusing the shared {@link ARN} parser.
   * S3 Batch Operations' {@code CreateJob} requires the account id to be passed explicitly (S3 Control is an account-scoped API).
   */
  private static String accountIdOf(String roleArn) {
    if (roleArn == null || !roleArn.contains(":")) {
      throw new IllegalArgumentException("Unable to derive AWS account id from S3_BATCH_OPS_ROLE_ARN: " + roleArn);
    }
    String accountId = new ARN(roleArn).getAccountId();
    if (accountId == null || accountId.isBlank()) {
      throw new IllegalArgumentException("Unable to derive AWS account id from S3_BATCH_OPS_ROLE_ARN: " + roleArn);
    }
    return accountId;
  }
}
