name: Manual Deploy to Artifactory

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: 'main'  # Change the default branch as needed

jobs:
  push-to-artifactory:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build XYZ hub jar
        run: mvn clean install -Pdocker -DskipTests=true -DdockerComposeFile=docker-compose-dynamodb.yml
      - name: Deploy to Artifactory
        run: mvn -gs $GITHUB_WORKSPACE/settings.xml --batch-mode deploy -Dmaven.test.skip=true -Partifactory
