name: Manual Deploy to Artifactory

#on:
#  push:
#    branches:
#      - master
#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Target branch'
#        required: true
#        default: 'main'  # Change the default branch as needed
on: [push, workflow_dispatch]

jobs:
  push-to-artifactory:
    runs-on: ubuntu-latest
    env:
      CODEARTIFACT_AUTH_TOKEN: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Deploy to AWS CodeArtifact
        run: mvn -gs $GITHUB_WORKSPACE/settings.xml --batch-mode deploy -Dmaven.test.skip=true -Pcom-here-ds
